#### general settings
name: latent_AutoEncoder
use_tb_logger: true
model: latent
distortion: mixed
gpu_ids: [3]
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: XYLQGT
    dataroot_X_GT: ./datasets/AE/train/X/GT #
    dataroot_X_LQ: ./datasets/AE/train/X/LQ
    dataroot_Y_GT: ./datasets/AE/train/Y/GT
    dataroot_Y_LQ: ./datasets/AE/train/Y/LQ

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 12
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    use_swap: true
    color: RGB
  val:
    name: Val_Dataset
    mode: XYLQGT
    dataroot_X_GT: ./datasets/AE/test/X/GT
    dataroot_X_LQ: ./datasets/AE/test/X/LQ
    dataroot_Y_GT: ./datasets/AE/test/Y/GT
    dataroot_Y_LQ: ./datasets/AE/test/Y/LQ

#### network structures
network_AE:
  which_model: UNet
  setting:
    in_ch: 3
    out_ch: 3
    ch: 8
    ch_mult: [4, 8, 8, 16]
    embed_dim: 8
#### path
path:
  #pretrain_model_G: /data1/haozhang/DDBF_PAMI/OmniFusion/v2/experiments/AutoEncoder-Multi_Modal/latent_AutoEncoder_archived_240518-215128/models/67200_G.pth
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 3e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 300000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5600

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5600
